"""initial schema

Revision ID: 1a2a6448d174
Revises: 
Create Date: 2026-10-03 10:07:14.257801+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a2a6448d174'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_topic'), ['topic'], unique=False)
        batch_op.create_index('ix_outbox_pending', ['published_at', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_email_lower', ['email'], unique=False)

    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_api_token_hash')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('workers',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('task_types', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index('ix_workers_active_seen', ['active', 'last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_owner_id'), ['owner_id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('default_max_parallel', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_owner_id'), ['owner_id'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('active_tasks', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_worker_id'), ['worker_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_parallel', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.String(length=32), nullable=True),
    sa.Column('triggered_by', sa.String(length=32), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index('ix_run_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_run_workflow_idempotency', ['workflow_id', 'idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cron_expression', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('overlap_policy', sa.String(length=24), nullable=False),
    sa.Column('catchup', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fired_slot', sa.String(length=64), nullable=True),
    sa.Column('last_run_id', sa.String(length=32), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'cron_expression', 'timezone', name='uq_schedule_identity')
    )
    with op.batch_alter_table('workflow_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_due', ['enabled', 'next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_schedules_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_schedules_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_schedules_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_secrets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'name', name='uq_workflow_secret_name')
    )
    with op.batch_alter_table('workflow_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_secrets_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workflow_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('published_by', sa.String(length=32), nullable=True),
    sa.Column('publish_note', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_version')
    )
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_versions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('run_events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('workflow_id', sa.String(length=32), nullable=True),
    sa.Column('step_run_id', sa.String(length=32), nullable=True),
    sa.Column('step_key', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_run_events_run_seq', ['run_id', 'seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_step_run_id'), ['step_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_events_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index('ix_run_events_workflow_seq', ['workflow_id', 'seq'], unique=False)

    op.create_table('step_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('step_key', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=200), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('retry_limit', sa.Integer(), nullable=False),
    sa.Column('backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('backoff_multiplier', sa.Double(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_token', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_key', name='uq_step_run_key')
    )
    with op.batch_alter_table('step_runs', schema=None) as batch_op:
        batch_op.create_index('ix_step_claimable', ['status', 'available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_runs_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_runs_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_runs_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_runs_worker_id'), ['worker_id'], unique=False)

    op.create_table('step_attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('step_run_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['step_run_id'], ['step_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_run_id', 'attempt_no', name='uq_step_attempt_no')
    )
    with op.batch_alter_table('step_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_attempts_step_run_id'), ['step_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_attempts_step_run_id'))

    op.drop_table('step_attempts')
    with op.batch_alter_table('step_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_runs_worker_id'))
        batch_op.drop_index(batch_op.f('ix_step_runs_task_type'))
        batch_op.drop_index(batch_op.f('ix_step_runs_status'))
        batch_op.drop_index(batch_op.f('ix_step_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_step_runs_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_step_runs_available_at'))
        batch_op.drop_index('ix_step_claimable')

    op.drop_table('step_runs')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index('ix_run_events_workflow_seq')
        batch_op.drop_index(batch_op.f('ix_run_events_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_run_events_step_run_id'))
        batch_op.drop_index('ix_run_events_run_seq')
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_run_events_created_at'))

    op.drop_table('run_events')
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_versions_workflow_id'))

    op.drop_table('workflow_versions')
    with op.batch_alter_table('workflow_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_secrets_workflow_id'))

    op.drop_table('workflow_secrets')
    with op.batch_alter_table('workflow_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_schedules_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_schedules_owner_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_schedules_next_run_at'))
        batch_op.drop_index('ix_schedule_due')

    op.drop_table('workflow_schedules')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_created_at'))
        batch_op.drop_index('ix_run_workflow_idempotency')
        batch_op.drop_index('ix_run_status_created')

    op.drop_table('workflow_runs')
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_recorded_at'))

    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_owner_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_name'))

    op.drop_table('workflows')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_workers_last_seen_at'))
        batch_op.drop_index('ix_workers_active_seen')

    op.drop_table('workers')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email_lower')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_pending')
        batch_op.drop_index(batch_op.f('ix_outbox_messages_topic'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_published_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_created_at'))

    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
